### ISSUE TITLE
Sample update(s) are successful, but the log shows an error

### ISSUE THREAD

**Issue by wow-such-code** [qbicsoftware/sample-tracking-update-portlet#7]
This error is thrown after a successfull update of sample Status/Location:

com.vaadin.event.ListenerMethod$MethodException: Invocation of method valueChange in life.qbic.portal.portlet.SampleTrackingUpdatePortlet$$Lambda$758/1282375828 failed.

**Comment by KochTobi** [comment]
Could not reproduce.
