### ISSUE TITLE
User_id column is not used to determine users available locations

### ISSUE THREAD

**Issue by wow-such-code** [qbicsoftware/sample-tracking-update-portlet#84]
**Describe the bug**
Users cannot update sample status because their available locations are not found and a nullpointer exception is thrown if their LDAP e-mail is different than their email in our production database persons table. This is independent of the email address found in "user_id"!

**To Reproduce**
1. Change your "email" field in the user db to something different
2. Try to use the portlet
3. Notice that the location selection is empty and throws an exception

**Expected behavior**
1. The available locations should depend on the user_id column. If your LDAP (Liferay) e-mail address is the same as in user_id, the locations connected to your user in the production database should be available from the dropdown.
2. If users don't have a location available, they should be informed and no error thrown.
3. This should also be logged.

**Additional context**
The root of the problem is most likely found in the sample-tracking-service and not in this portlet.
Workaround: change user "email" field to their login email. This should be reversed ASAP as it changes the users email used on new offers, which might be undesirable.

**Comment by KochTobi** [comment]
This was addressed and fixed in https://github.com/qbicsoftware/sample-tracking-service/pull/35
The resolution of email/user_id to location is now done by the service. The endpoint is the same, therefore no change in the portlet was needed.
